# Site settings
author: Jonathan Chasse
title: Why in the world do I want to code?
header-img: img/home-bg.png
email: jonathan.r.chasse@gmail.com
copyright_name: Jonathan Chasse
description: > # this means to ignore newlines until "baseurl:"
  Rational, opportunity, future of work, entrepreneur, family
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jchasse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
